language: python
python:
  - "2.7"
  - "3.5"
env:
  - PROJECT=static_map_generator MAPNIK_VERSION=3.0.10 PYTHON_MAPNIK_COMMIT=3a60211dee366060acf4e5e0de8b621b5924f2e6
notifications:
  email:
    - cahytinne@geosolutions.be
before_install:
  - sudo apt-get -qq update libcairo-dev python-cairo-dev
  - sudo apt-get install -y --no-install-recommends libxml2-dev
  - curl -s https://mapnik.s3.amazonaws.com/dist/v${MAPNIK_VERSION}/mapnik-v${MAPNIK_VERSION}.tar.bz2 | tar -xj -C /tmp/
  - (cd /tmp/mapnik-v${MAPNIK_VERSION} && python scons/scons.py configure)
  - (cd /tmp/mapnik-v${MAPNIK_VERSION} && make JOBS=4 && make install JOBS=4)
  - (mkdir -p /opt/python-mapnik && curl -L https://github.com/mapnik/python-mapnik/archive/${PYTHON_MAPNIK_COMMIT}.tar.gz | tar xz -C /opt/python-mapnik --strip-components=1)
  - (cd /opt/python-mapnik && python2 setup.py install && python3 setup.py install && rm -r /opt/python-mapnik/build)
#  - git clone git@github.com:OnroerendErfgoed/oeauth.git
#  - (cd oeauth && git checkout 1.1.0)
#  - git clone git@github.com:OnroerendErfgoed/pyramid_oeauth.git
#  - (cd pyramid_oeauth && git checkout 1.2.0)
install:
  - pip install -r requirements-dev-tci.txt
  - python setup.py develop
script:
  py.test --cov $PROJECT --cov-report term-missing tests