language: python
dist: focal
python:
  - "3.8"
virtualenv:
  system_site_packages: true
before_install:
  - pip install git+https://git@github.com/OnroerendErfgoed/wsgicoers.git@0.9.0
  - sudo apt-get update
  - sudo apt-get install libmapnik3.0 libmapnik-dev mapnik-utils python3-mapnik libmagickwand-dev
install:
  - pip freeze
  - pip3 freeze
  - pip install -r requirements-tci.txt
  - python setup.py develop
script:
  py.test --cov $PROJECT --cov-report term-missing tests
