language: python
python:
  - "3.6"
env:
  - PROJECT=static_map_generator MAPNIK_VERSION=3.1.0 PYTHON_MAPNIK_COMMIT=a2c2a86eec954b42d7f00093da03807d0834b1b4 PYTHON=python
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y --no-install-recommends libboost-all-dev git tar unzip wget bzip2 build-essential autoconf libtool libxml2-dev libgeos-dev libgeos++-dev libpq-dev libbz2-dev libproj-dev munin-node munin protobuf-c-compiler libfreetype6-dev libtiff5-dev libicu-dev libgdal-dev libcairo2-dev libcairomm-1.0-dev apache2 apache2-dev libagg-dev liblua5.2-dev ttf-unifont lua5.1 liblua5.1-0-dev
  - wget -c https://github.com/mapnik/mapnik/releases/download/v${MAPNIK_VERSION}/mapnik-v${MAPNIK_VERSION}.tar.bz2 -O - | tar -xj -C /tmp/
  - (cd /tmp/mapnik-v${MAPNIK_VERSION} && ${PYTHON} scons/scons.py configure)
  - (cd /tmp/mapnik-v${MAPNIK_VERSION} && sudo make JOBS=4 && sudo make install JOBS=4)
  - (mkdir -p /opt/python-mapnik && curl -L https://github.com/mapnik/python-mapnik/archive/${PYTHON_MAPNIK_COMMIT}.tar.gz | tar xz -C /opt/python-mapnik --strip-components=1)
  - (cd /opt/python-mapnik && python setup.py install && rm -r /opt/python-mapnik/build)

  - pip install git+ssh://git@github.com/OnroerendErfgoed/oeauth.git@1.3.0
  - pip install git+ssh://git@github.com/OnroerendErfgoed/wsgicoers.git@0.9.0
  - pip install git+ssh://git@github.com/OnroerendErfgoed/pyramid_oeauth.git@2.0.1
install:
  - pip install -r requirements-tci.txt
  - python setup.py develop
script:
  py.test --cov $PROJECT --cov-report term-missing tests
