language: python
python:
  - "2.7"
  #- "3.5"
env:
  - PROJECT=static_map_generator MAPNIK_VERSION=3.0.10 PYTHON_MAPNIK_COMMIT=3a60211dee366060acf4e5e0de8b621b5924f2e6 PYTHON=python2
notifications:
  email:
    - cahytinne@geosolutions.be
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y --no-install-recommends libboost-dev libboost-filesystem-dev libboost-program-options-dev libboost-python-dev libboost-regex-dev libboost-system-dev libboost-thread-dev libicu-dev libtiff5-dev libfreetype6-dev libpng12-dev libxml2-dev libproj-dev libsqlite3-dev libgdal-dev libcairo-dev python-cairo-dev postgresql-contrib libharfbuzz-dev
  - curl -s https://mapnik.s3.amazonaws.com/dist/v${MAPNIK_VERSION}/mapnik-v${MAPNIK_VERSION}.tar.bz2 | tar -xj -C /tmp/
  - (cd /tmp/mapnik-v${MAPNIK_VERSION} && ${PYTHON} scons/scons.py configure)
  - (cd /tmp/mapnik-v${MAPNIK_VERSION} && sudo make JOBS=4 && sudo make install JOBS=4)
  - (mkdir -p /opt/python-mapnik && curl -L https://github.com/mapnik/python-mapnik/archive/${PYTHON_MAPNIK_COMMIT}.tar.gz | tar xz -C /opt/python-mapnik --strip-components=1)
  - (cd /opt/python-mapnik && python setup.py install && rm -r /opt/python-mapnik/build)
install:
  - pip install -r requirements-tci.txt
  - python setup.py develop
script:
  py.test --cov $PROJECT --cov-report term-missing tests